### PR TITLE
Light Component become stained by ColorModifier

### PR DESCRIPTION
**Pull request by camilla-ett**
like this

### CODE REVIEW

**Comment by xenxero1** [comment]
Could you possible do something similar with the Starfall/Starstrike effect? Every color applied seems to turn the particles straight black.

**Comment by camilla-ett** [comment]
I will try it, but I dont know how does work it normal.... ( am2 1.7.10 works it?

**Comment by xenxero1** [comment]
i was never able to get it to work in 1.7.10's version sadly. Only tested with purple and yellow. Potentially something to do with the default dye being black/ink sacs?

Edit: https://github.com/Growlith1223/ArsMagica2/issues/227

**Comment by Growlith1223** [comment]
nice

**Pull request merged**
