### PR TITLE
Fix Randomteleport,Disarm,ManaBattery 1.10.2

### LINKED ISSUE #58: Version 1.5.0-9: Disarm does not work on mobs
Using projectile disarm does not affect zombies, skeletons and zombie pig-mans at all. Most likely to not work on other mobs as well.

*Still works on players

### PR DESCRIPTION
**Pull request by Orinion**
Fixed Randomteleport doing nothing.#91
However, the randomLocation is still likely to be in the ground, resulting in
not teleporting. 
Also Fixed #58
You might want to increase the PickupDelay.

### CODE REVIEW

**Comment by ProfHugo** [comment]
With 1.9 adding the ability to carry items in offhand, would it be nice if disarm also drop held items in offhand aswell?

**Comment by Orinion** [comment]
Fixed #117

**Comment by Orinion** [comment]
Yeah, maybe when combined with a power modifier

**Comment by ProfHugo** [comment]
Just wondering, in line 54 and 55:
```
if (target instanceof EntityPlayer && ((EntityPlayer)target).getActiveItemStack() != null && !target.worldObj.isRemote){
			if (EnchantmentHelper.getEnchantmentLevel(AMEnchantments.soulbound, ((EntityPlayer)target).getActiveItemStack()) > 0)
				return true;
			((EntityPlayer)target).dropItem(true);
			return true;
		}
```

getActiveItemStack is still used with soulbound check, and if it were to be true that this method is deprecated, then wouldn't this also cease to work?

**Pull request merged**
