### PR TITLE
Cloaks.

### PR DESCRIPTION
**Pull request by TheIcyOne**
Cloaks? Cloaks.

About 50% of this is directly from 1.7.10.

### CODE REVIEW

**Comment by xenxero1** [comment]
Just looking at the code quickly, seems to have a ton of model rendering effects (presumably for the cloaks). Can we get a config to disable this clientside? One of am2's strong points is it being fairly resource conservative.

**Comment by TheIcyOne** [comment]
It literally only renders on a few players, and I'm not sure many of them even play Minecraft anymore.

**Comment by Growlith1223** [comment]
this mod has never been resource conservative lol, look at how many textures there are... performance wise, yes it was good, but resource wise, not even close.

**Comment by xenxero1** [comment]
Ahh ok, I wasn't familiar with how they worked. Thought it was more like a Botania's Cloaks; special equipment with cosmetics and function. 

How would one go about getting on to the list? None of the names ring a bell, and I hope that's not the donor list with how short it is 😞.

https://qorconcept.com/mc/AREW0152.txt

**Comment by TheIcyOne** [comment]
We have a list that Mithion set up originally, and also a few contributors I added manually which are basically just Growl and JJT.

**Comment by xenxero1** [comment]
Any plans to open the list at some point to donors? 

I'm regarded on my server as 'The God of Magic'. It'd be worth my while to throw some dough to get a fitting cape/aura!

Also; Question. Does invisibility stop the cape/aura form displaying? Seems like it would be self-defeating in a pvp or mischievous setting.

**Comment by Growlith1223** [comment]
that's honestly up to mithion if he wants to open that back up.

if he doesn't i /may/? i'd feel cheap about doing that tho.

**Comment by renadi** [comment]
Yeah, I'm still donating to motion, but I'd appreciate being able to donate
something to growlith if posible.

**Comment by xenxero1** [comment]
Should we ping him? Try to get an answer?
Mithion I mean.

**Comment by Growlith1223** [comment]
i could message him on twitter lol

**Comment by TheIcyOne** [comment]
Just to note, I don't think auras are implemented yet. It is possible I did them by accident, though.

**Comment by xenxero1** [comment]
Just wanted to see if we got an update on this situation.

**Comment by Growlith1223** [comment]
haven't gotten a reply yet. and probably won't work on this until i get situated in a new house from moving(im moving so commits will be on hiatus for a little while(depends on how lucky i am for internet))

**Pull request merged**
