### PR TITLE
Fixed magic armor being damaged  by void damage (Port of Mithion/ArsMagica2#1500)

### PR DESCRIPTION
**Pull request by jjtParadox**
Just a port of Mithion/ArsMagica2#1500 that didn't make it into this fork.

### CODE REVIEW

**Comment by TheIcyOne** [comment]
I think this is covered by the changes from #236, as outOfWorld damage is unblockable.

**Comment by jjtParadox** [comment]
Oh yeah you're probably right about that. I'll test it later just in case!

**Comment by TheIcyOne** [comment]
From my testing, the #236 changes covered it in 1.11 versions, and it should be the same in 1.10, but I don't have an instance lying around to test with.

**Comment by jjtParadox** [comment]
Yup #236 fixed it.

**Pull request closed without merging**
