### PR TITLE
Fix of unable to summon Bosses

### PR DESCRIPTION
**Pull request by camilla-ett**
Fix
 - LifeGuardian
 - EnderGuardian
 - WinterGuardian (#224)

### CODE REVIEW

**Comment by xenxero1** [comment]
Idk man, I was able to summon him just fine on the -17b release. In fact, I was farming him last night!

**Comment by xenxero1** [comment]
Would you be able to extend this to the Winter guardian?

Or is the code not the same?

**Comment by camilla-ett** [comment]
@xenxero1 I got it. it's the same way to fix. thank you for your ponting it out.

**Comment by camilla-ett** [comment]
Can anyone fix missing texture of IceEffigy?

**Comment by xenxero1** [comment]
According to the ReadMe, a similar issue occurs with the Lightning Guardian.

**Pull request merged**
